name: Deploy CI

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run Scraper
        run: deno run --allow-all utils/scrape.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "xinitra"
          entrypoint: "./mod.ts" # TODO(uwussimo): update